### ISSUE TITLE
Code completion not working

### ISSUE THREAD

**Issue by messutied** [stollcri/elixir.novaextension#1] opened 2020-09-18 07:14 UTC
Hi,

I've installed this extension and only syntax highlighting seems to work, no code completion seems to be taking place.

Is there a way to see if there are runtime errors or something? I'm new to the editor and I see no obvious errors messages.

**Comment by stollcri** [comment] 2020-10-01 11:13
Closing, I cannot reproduce your issue
There is an extension console to check for problems, but this extension only uses built-in Nova functionality

**Closed as completed by stollcri** 2020-10-01 11:13 UTC
